language: python
python: "2.7"

sudo: required

branches:
  only:
    - master
    - dev

addons:
  apt:
    packages:
      - python-pip

install:
  - pip install ansible

  # version checks
  - ansible --version

script:
  - ansible-playbook playbook.yml --syntax-check
  - ansible-playbook playbook.yml -c local -b
  # add other playbooks here...

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
