Vagrant.configure("2") do |config|

  config.vm.provider "{{ cookiecutter.vagrant_provider }}" do |v|
      v.memory = {{ cookiecutter.vagrant_ram }}
      v.cpus = {{ cookiecutter.vagrant_cpus }}
  end
  
  config.vm.define "ansible", autostart: "True" do |ansible|
      ansible.vm.box = "{{ cookiecutter.vagrant_box }}"
      ansible.vm.hostname = "ansible-play-{{ cookiecutter.playbook_name }}"

      ansible.vm.provision "shell", inline: "sudo yum -y install epel-release && sudo yum -y install git vim python-pip"
      ansible.vm.provision "shell", inline: "sudo pip install ansible"
      ansible.vm.provision "file", source: ".", destination: "{{ cookiecutter.vagrant_play_path }}"
      ansible.vm.provision "shell", inline: "(cd {{ cookiecutter.vagrant_play_path }} && [ -f roles/requirements.yml ] && ansible-galaxy install -r roles/requirements.yml) || echo 'No requirements file found, skipping Galaxy installs...'"
      ansible.vm.provision "shell", inline: "(cd {{ cookiecutter.vagrant_play_path }} && [ -f playbook.yml ] && ansible-playbook -v playbook.yml) || echo 'No playbook found, continuing without running Ansible...'"

  end
end
