Vagrant.configure("2") do |config|

  # Defining hardware parameters for the vm
  config.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 2
  end

  config.vm.define "ansible", autostart: "True" do |ansible|
      ansible.vm.box = "centos/7"
      ansible.vm.hostname = "ansible"

      ansible.vm.provision "file", source: ".", destination: "/tmp/ansible-play"
      ansible.vm.provision "shell", inline: "sudo yum -y install epel-release && sudo yum -y install git vim python-pip"
      ansible.vm.provision "shell", inline: "sudo pip install ansible"
      ansible.vm.provision "shell", inline: "(cd /tmp/ansible-play && [ -f roles/requirements.yml ] && ansible-galaxy install -r roles/requirements.yml) || echo 'No requirements file found, skipping Galaxy installs...'"
      ansible.vm.provision "shell", inline: "(cd /tmp/ansible-play && [ -f playbook.yml ] && ansible-playbook -v playbook.yml) || echo 'No playbook found, continuing without running Ansible...'"

  end
end
